-- MySQL Script generated by MySQL Workbench
-- Fri Aug 17 20:37:32 2018
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS = @@UNIQUE_CHECKS, UNIQUE_CHECKS = 0;
SET @OLD_FOREIGN_KEY_CHECKS = @@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS = 0;
SET @OLD_SQL_MODE = @@SQL_MODE, SQL_MODE = 'TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema periodicals
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema periodicals
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `periodicals`
  DEFAULT CHARACTER SET utf8mb4
  COLLATE utf8mb4_0900_ai_ci;
USE `periodicals`;

-- -----------------------------------------------------
-- Table `periodicals`.`payment`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`payment` (
  `id`    INT(11)        NOT NULL AUTO_INCREMENT,
  `date`  TIMESTAMP      NOT NULL,
  `price` DECIMAL(10, 0) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 4
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `periodicals`.`periodical_category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`periodical_category` (
  `id`       INT(11)     NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(50) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 13
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `periodicals`.`periodical_type`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`periodical_type` (
  `id`   INT(11)     NOT NULL AUTO_INCREMENT,
  `type` VARCHAR(30) NULL     DEFAULT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 4
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `periodicals`.`periodical`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`periodical` (
  `id`          INT(11)        NOT NULL AUTO_INCREMENT,
  `title`       VARCHAR(45)    NOT NULL,
  `type`        INT(11)        NOT NULL,
  `category`    INT(11)        NOT NULL,
  `period`      VARCHAR(50)    NULL     DEFAULT NULL,
  `price`       DECIMAL(10, 0) NOT NULL,
  `description` TEXT           NULL     DEFAULT NULL,
  PRIMARY KEY (`id`),
  INDEX `FK_category` (`category` ASC),
  INDEX `FK_type_idx` (`type` ASC),
  CONSTRAINT `FK_category`
  FOREIGN KEY (`category`)
  REFERENCES `periodicals`.`periodical_category` (`id`),
  CONSTRAINT `FK_type`
  FOREIGN KEY (`type`)
  REFERENCES `periodicals`.`periodical_type` (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 4
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `periodicals`.`user_role`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`user_role` (
  `id`   INT(11)     NOT NULL AUTO_INCREMENT,
  `role` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 4
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `periodicals`.`user`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`user` (
  `id`       INT(11)     NOT NULL AUTO_INCREMENT,
  `role`     INT(11)     NOT NULL,
  `name`     VARCHAR(30) NOT NULL,
  `login`    VARCHAR(30) NOT NULL,
  `password` VARCHAR(30) NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `login_UNIQUE` (`login` ASC),
  INDEX `FK_role` (`role` ASC),
  CONSTRAINT `FK_role`
  FOREIGN KEY (`role`)
  REFERENCES `periodicals`.`user_role` (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 24
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;

-- -----------------------------------------------------
-- Table `periodicals`.`subscription`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `periodicals`.`subscription` (
  `id`              INT(11)   NOT NULL AUTO_INCREMENT,
  `user_id`         INT(11)   NOT NULL,
  `periodical_id`   INT(11)   NOT NULL,
  `payment_id`      INT(11)   NOT NULL,
  `expiration_date` TIMESTAMP NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `paymentId_UNIQUE` (`payment_id` ASC),
  INDEX `FK_periodicalId` (`periodical_id` ASC),
  INDEX `FK_userId` (`user_id` ASC),
  CONSTRAINT `FK_paymentId`
  FOREIGN KEY (`payment_id`)
  REFERENCES `periodicals`.`payment` (`id`),
  CONSTRAINT `FK_periodicalId`
  FOREIGN KEY (`periodical_id`)
  REFERENCES `periodicals`.`periodical` (`id`),
  CONSTRAINT `FK_userId`
  FOREIGN KEY (`user_id`)
  REFERENCES `periodicals`.`user` (`id`)
)
  ENGINE = InnoDB
  AUTO_INCREMENT = 4
  DEFAULT CHARACTER SET = utf8mb4
  COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE = @OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS = @OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS = @OLD_UNIQUE_CHECKS;
